imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ['127.0.0.1']
    session:
        save_path: %session_save_path%
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ 'FOSCommentBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        #metadata_cache_driver: apc
        #query_cache_driver: apc
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

liip_theme:
    themes: %liip_themes%
    active_theme: %liip_active_theme%
    autodetect_theme: %liip_autodetect_theme%
    load_controllers: %liip_load_controllers%
    cookie:
        name: matuckLibrary
        lifetime: 31536000 # 1 year in seconds
        path: /
        domain: ~
        secure: false
        http_only: false
        
fpn_tag:
    model:
        tag_class:     matuck\LibraryBundle\Entity\Tag
        tagging_class: matuck\LibraryBundle\Entity\Tagging
        
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: matuck\LibraryBundle\Entity\User
    
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable : true
            timestampable: false # not needed: listeners are not enabled by default

ivory_lucene_search:
    # Index identifier
    master:
        # Path to store the index (Required)
        path: %kernel.root_dir%/cache/searchindexes/master
        analyzer: Zend\Search\Lucene\Analysis\Analyzer\Common\TextNum\CaseInsensitive

gregwar_captcha:
    as_url: true
    
fos_comment:
    db_driver: orm
    class:
        model:
            comment: matuck\LibraryBundle\Entity\Comment
            thread: matuck\LibraryBundle\Entity\Thread
    acl: true
    form:
        comment:
            type: app_comment
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
liip_cache_control:
      rules:
          - { controller: ^GregwarCaptchaBundle:Captcha:generateCaptcha$, controls: [ no-cache ], vary: [Accept-Encoding, Accept-Language] }
